### PR TITLE
osu! requests + rate limiter / config database

### PR DESCRIPTION
**Pull request by nicholastay**
osu! request handling alongside rate limiting

### CODE REVIEW

**Comment by n2468txd** [comment]
BTW, the exrated branch is exactly the same a plugin.ex in this branch, so you may want to merge that one first then I can merge the new upstream/master into here then that change will be redundant.

:P

**Comment by michaelowens** [comment]
There's conflicts before I can merge this, can you resolve them by merging my master branch into your osu_requests branch? (probably because I just did the other PR)

Also, what happens now with messages that fall in the rate limit? Do they get delayed or never sent?

**Comment by n2468txd** [comment]
Conflict has been resolved.

In response to your second question, the messages that fall into the rate limit get kept in a list and are sent slowly by the RateLimiting module.

**Comment by n2468txd** [comment]
Toggleable osu! requests added

Also for store in database, I didn't know whether to put them here in the same branch so:
https://github.com/n2468txd/xikbot/tree/osu_requests_config

I can merge them if you wanted it all in one.

**Comment by michaelowens** [comment]
Ah yes, please do it in one branch as this won't be merged without it.

**Pull request closed without merging**
